### PR TITLE
Google Movies fully working now

### PR DESCRIPTION
**Pull request by ivannieto**

### CODE REVIEW

**Comment by shivam5992** [comment]
Thanks for the good work

**Comment by ivannieto** [comment]
Thanks a lot. Enjoying to learn that way. Anyway can I make it mine as an updated and mantained revision in my own account under my own name? Would be great for both as you don't need to be merging every PR

**Comment by shivam5992** [comment]
Sure 👍

**Comment by ivannieto** [comment]
Thanks a lot! I'll do asap.

**Pull request merged**
